### ISSUE TITLE
Analyse efforts for improving section 85 (COT)

### ISSUE THREAD

**Issue by melovictor** [firefoxpdm/gamebooks#7]
This smells very bad and looks even worse then it smells. When I finish with the translation I will have a deeper look at it...

**Comment by firefoxpdm** [comment]
It doesn't smell, it speaks about lazyness :) Fixed 248-85, 201, 187-260, 113-141. There are still some left to fix. Might require further changes in the item checking though...

**Comment by firefoxpdm** [comment]
Okay, technically this is done.
